#!/usr/bin/env python3
"""icloud-nfs-exporter CLI tool."""

import argparse
import sys


def cmd_setup(_args):
    print("setup: not yet implemented")


def cmd_add_folder(_args):
    print("add-folder: not yet implemented")


def cmd_diagnose(_args):
    print("diagnose: not yet implemented")


def main():
    parser = argparse.ArgumentParser(
        prog="icne",
        description="icloud-nfs-exporter CLI",
    )
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("setup", help="Initial setup and configuration")
    sub.add_parser("add-folder", help="Add an iCloud folder to export")
    sub.add_parser("diagnose", help="Run diagnostics")

    args = parser.parse_args()
    if args.command is None:
        parser.print_help()
        sys.exit(1)

    commands = {
        "setup": cmd_setup,
        "add-folder": cmd_add_folder,
        "diagnose": cmd_diagnose,
    }
    commands[args.command](args)


if __name__ == "__main__":
    main()
